In [267]:
#1 Some problems can be solved through recrusion only Answer: FALSE
# Find an example that can be solved by recursion loops.

# Program to print the fibonacci series upto n_terms
 
# Recursive function
def recursive_fibonacci(n):
  if n <= 1:
      return n
  else:
      return(recursive_fibonacci(n-1) + recursive_fibonacci(n-2))
 
n_terms = 10
 
# check if the number of terms is valid
if n_terms <= 0:
  print("Invalid input ! Please input a positive value")
else:
  print("Fibonacci series:")
for i in range(n_terms):
    print(recursive_fibonacci(i))



Fibonacci series:
0
1
1
2
3
5
8
13
21
34


In [268]:
# 2. Recursive Lines
# Write a recursive function toaccept integer n
# display a star on line 1,* line 2** lin 3***
#the Output should look like
# *
# **
# ***

# Recursive line pattern
print('Output:')
def printPatternRowRecur(n):
 
    # base condition
    if (n < 3):
        return
         
    # print the remaining
    # stars of the n-th row
    # recursively
    print("*", end = " ")
    printPatternRowRecur(n - 1)
 
def printPatternRecur(n):
 
    # base condition
    if (n < 1):
        return
     
   # print the stars of
    # the n-th row
    printPatternRowRecur(n)
     
    # move to next line
    print("")
     
    # remaining rows recursively
    # base condition
    if (n > 4):
        return

    # print stars of the
    # remaining rows recursively
    printPatternRecur(n + 1)
     
# Driver Code
n = 3
printPatternRecur (n)

Output:
* 
* * 
* * * 


In [269]:
#3 Largest list item
# Write a function that accepts a list as an agrument
# and returns the largest value in the list
# Use Recursion function to find largest value

print('Largest Number in the List:')
def findMinRec(A, n):
     
    # if size = 0 means whole array
    # has been traversed
    if (n == 1):
        return A[0]
    return min(A[n - 1], findMinRec(A, n - 1))
 
# Driver Code
if __name__ == '__main__':
    A = [1, 4, 45, 6, -50, 10, 2]
    n = len(A)
    print(findMinRec(A, n))

Largest Number in the List:
-50


In [270]:
#3b Rercursive Line, sum numbers 1:50
# Python code to find sum
# of natural numbers up to
# n using recursion
 
# Returns sum of first
# n natural numbers
def recurSum(n):
    if n <= 1:
        return n
    return n + recurSum(n - 1)
 
# Driver code
n = 32
print(recurSum(n))

528


In [ ]:
#4 Ackermann Fuction

In [271]:
#5 Create Numpy array of all 1's
#
import numpy as np
a = np.ones(4, dtype = int)
print("Matrix a : \n", a)
 
b = np.ones([5, 5], dtype = int)
print("\nMatrix b : \n", b)

Matrix a : 
 [1 1 1 1]

Matrix b : 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [272]:
#6. Remove rows containing NaN using Bitwise NOT operator
#   and np.isnan() function
#NaN values are removed with numpy by identifying rows ix that contain NaN.
#Next, the rows are removed with z=z[~iz] 
#where ~ is a bitwise not operator.

import numpy as np
z = np.array([[      1,      2],
              [ np.nan,      3],
              [      4, np.nan],
              [      5,      6]])
iz = np.any(np.isnan(z), axis=1)
print(~iz)
z = z[~iz]
print(z)


[ True False False  True]
[[1. 2.]
 [5. 6.]]


In [274]:

#Ackermann algorithm: 
 # Python program to illustrate Ackermann function
 # Code applying first condition, second condition third...of
 # Acckermann Function
def A(m, n, s ="% s"):
    print(s % ("A(% d, % d)" % (m, n)))
    if m == 0:
        return n + 1
    if n == 0:
        return A(m - 1, 1, s)
    n2 = A(m, n - 1, s % ("A(% d, %% s)" % (m - 1)))
    return A(m - 1, n2, s)
 
print(A(1, 2))
 

A( 1,  2)
A( 0, A( 1,  1))
A( 0, A( 0, A( 1,  0)))
A( 0, A( 0, A( 0,  1)))
A( 0, A( 0,  2))
A( 0,  3)
4
